import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Open_Sans,
    Inter,
    Roboto,
    Lexend,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

const lexend = Lexend({
    variable: "--font-lexend",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${inter.variable} ${roboto.variable} ${lexend.variable} antialiased`}
            >
                <nav className="sticky top-0 left-0 w-full mb-10 h-12 md:h-14 bg-black text-white">
                    {/* Placeholder Navbar */}
                </nav>
                {children}
            </body>
        </html>
    );
}
