import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "@/app/globals.css";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProtectedRoute allowedRoles={["client", "admin"]}>
            {children}
        </ProtectedRoute>
    );
}
